apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/sonar
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      securityContext:
        fsGroup: 1000

    spec:
      containers:
      - name: sonarqube
        image: sonarqube:lts

        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: sonar-data
          mountPath: /opt/sonarqube/data
      volumes:
      - name: sonar-data
        persistentVolumeClaim:
          claimName: sonar-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30009
